### PR TITLE
Define "open data" as being license-free.

### PR DESCRIPTION
**Pull request by kfogel**
Insert the language from http://opengovdata.org/ ("The 8 Principles of
Open Government Data") about open data being license-free into the
defintion of "open data".

### CODE REVIEW

**Comment by freegovinfo** [comment]
wholeheartedly agree!

**Comment by DanielSchuman** [comment]
I'll add the link in a bit, but I wrote about this Iin a comment. Suggested
adding a new section to appendix 2 that goes into significant detail on
evaluating compliance with these standards. (Actually 10 points, also
including a few new items).

On Friday, November 20, 2015, James R. Jacobs <notifications@github.com>
wrote:

> wholeheartedly agree!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ombegov/a130/pull/68#issuecomment-158533981>.
>


-- 
- Daniel
(Please excuse typos, send by phone )

**Comment by konklone** [comment]
Big :+1:!

**Comment by DanielSchuman** [comment]
Assuming I did this right, here's the link to the updates to [appendix2](https://github.com/ombegov/a130/pull/44). You can see the substance of the recommended changes [here](https://github.com/ombegov/a130/pull/44/files) starting at line 57.

**Pull request closed without merging**
